#!/bin/bash
. /.denv
if [[ "$BIRD" == 1 ]]; then
  echo "bird enabled, start bird_ctl"
  set +e
  rm /var/run/bird.sock
  exec socat UNIX-LISTEN:/var/run/bird.ctl,fork,reuseaddr TCP4:127.0.0.1:$BIRD_CTL_PORT
else
  echo "bird not enabled, bird_ctl down"
  sv down bird_ctl
  exec sleep infinity
fi
