#!/bin/bash
. /.denv
if [[ "$BIRD" == 1 ]]; then
  set -x
  echo "bird enabled, start"
  wget https://dn42.burble.com/roa/dn42_roa_bird2_4.conf -O /etc/bird/roa_dn42.conf.tmp -t 3 -q && mv /etc/bird/roa_dn42.conf.tmp /etc/bird/roa_dn42.conf
  wget https://dn42.burble.com/roa/dn42_roa_bird2_6.conf -O /etc/bird/roa_dn42_v6.conf.tmp -t 3 -q && mv /etc/bird/roa_dn42_v6.conf.tmp /etc/bird/roa_dn42_v6.conf
  birdc configure
  sleep $((RANDOM % 30000 + 30000))
else
  echo "bird not enabled, down"
  sv down bird_roa_download
  exec sleep infinity
fi
