#!/bin/bash
. /.denv
if [[ "$BIRD" == 1 ]]; then
  set -e
  set -x
  echo "bird enabled, start"
  wget https://dn42.burble.com/roa/dn42_roa_bird2_4.conf -O /etc/bird/roa_dn42.conf.tmp -t 3 && mv /etc/bird/roa_dn42.conf.tmp /etc/bird/roa_dn42.conf || ( sleep 5;exit 1)
  wget https://dn42.burble.com/roa/dn42_roa_bird2_6.conf -O /etc/bird/roa_dn42_v6.conf.tmp -t 3 && mv /etc/bird/roa_dn42_v6.conf.tmp /etc/bird/roa_dn42_v6.conf || (sleep 5; exit 1)
  set +e
  birdc configure
  sleep $((RANDOM % 30000 + 30000))
else
  echo "bird not enabled, down"
  sv down bird_roa_download
  exec sleep infinity
fi