#!/bin/bash
. /.denv
if [[ "$VPP" == 1 ]]; then
  echo "vpp enabled, start"
  template="/etc/vpp/startup.cli.template"
  conf="/etc/vpp/startup.cli"
  cat $template | sed -e 's/\${/＄/g' | sed 's/\$/${DOLLAR}/g' | sed 's/＄/${/g' | envsubst > $conf
  exec vpp -c /etc/vpp/startup.conf
else
  echo "vpp not enabled, down"
  sv down vpp
  exec sleep infinity
fi
