#!/bin/bash
set +e
/etc/init.d/ssh start
/etc/init.d/cron start
/etc/init.d/syslog-ng start

mkdir -p /home/root/.rootfs/etc/sv
touch    /home/root/.rootfs/etc/crontab


if [[ ! -e /home/root/.rootfs/etc/rc.local ]]; then
    echo "First run"
    rsync -a /tmp/.[^.]* /home/root
	
	cat > /home/root/.rootfs/etc/rc.local << EOL
#!/bin/bash
/etc/init.d/nginx start
rsync -a --no-perms --no-owner --no-group /home/root/.rootfs/etc/sv/* /etc/service
apt-get update
EOL
    chmod 755 /home/root/.rootfs/etc/rc.local
	
	mkdir -p  /home/root/.rootfs/var/www/html
	rsync -a /var/www/html/* /home/root/.rootfs/var/www/html
	ln -s ../../home/root/.rootfs/var/www/html /var/www/html
fi

parser=$(head -n 1 /etc/rc.local)
eval ${parser:2} /etc/rc.local
