#!/bin/bash
. /.denv
if [[ "$EG" == 1 ]]; then
  echo "etherguard enabled, start"
  template="/etc/eggo/edge.yaml.template"
  conf="/etc/eggo/edge.yaml"
  cat $template | sed -e 's/\${/＄/g' | sed 's/\$/${DOLLAR}/g' | sed 's/＄/${/g' | envsubst > $conf
  exec etherguard-go -config /etc/eggo/edge.yaml -mode edge
else
  echo "etherguard not enabled, down"
  sv down etherguard
  exec sleep infinity
fi
