#!/bin/bash
. /.denv
if [[ "$DN42AP" == 1 ]]; then
  echo "dn42ap enabled, start"
  if [ ! -d /etc/dn42ap_py ]; then
    echo "Directory not found!"
    if [[ -d /ext ]]; then
      ln -s /ext/DN42-AutoPeer /etc/dn42ap_py
    else
      git clone --depth 1 https://github.com/KusakabeSi/DN42-AutoPeer.git /etc/dn42ap_py
    fi
    chmod 755 /etc/dn42ap_py/*
  fi
  if birdc s p ; then
    true
  else
    echo "BIRD not ready, wait 8 seconds"
    exec sleep 8
  fi
  cd /etc/dn42ap_py
  git pull
  exec python3 /etc/dn42ap_py/DN42AutoPeer.py
else
  echo "dn42ap not enabled, down"
  sv down dn42ap
  exec sleep infinity
fi
