#!/bin/bash
. /.denv
if [[ "$DN42AP" == 1 ]]; then
  echo "dn42ap enabled, start"
  if [ ! -d /etc/dn42ap_py ]; then
    echo "Directory not found!"
    git clone --depth 1 https://github.com/KusakabeSi/DN42-AutoPeer-vpp /etc/dn42ap_py
    #ln -s /ext/DN42-AutoPeer /etc/dn42ap_py
    chmod 755 /etc/dn42ap_py/*
  fi
  cd /etc/dn42ap_py
  exec python3 /etc/dn42ap_py/DN42AutoPeer.py
else
  echo "dn42ap not enabled, down"
  sv down dn42ap
  exec sleep infinity
fi
