#!/bin/bash
. /.denv
if [[ "$DN42AP_WHOIS" == 1 ]]; then
  echo "dn42ap_whois enabled, start"
  if [ ! -d /etc/dn42ap_py ]; then
    echo "Directory not found!"
    if [[ -d /ext ]]; then
      ln -s /ext/DN42-AutoPeer /etc/dn42ap_py
    else
      git clone --depth 1 https://github.com/KusakabeSi/DN42-AutoPeer.git /etc/dn42ap_py
    fi
    chmod 755 /etc/dn42ap_py/*
  fi
  cd /etc/dn42ap_py
  git pull
  exec python3 /etc/dn42ap_py/DN42whois.py
else
  echo "dn42ap_whois not enabled, down"
  sv down dn42ap_whois
  exec sleep infinity
fi
