#!/bin/bash
. /.denv
if [[ "$DN42AP_WHOIS" == 1 ]]; then
  echo "dn42ap_whois enabled, start"
  cd /etc/dn42ap_py
  exec python3 /etc/dn42ap_py/DN42whois.py
else
  echo "dn42ap_whois not enabled, down"
  sv down dn42ap_whois
  exec sleep infinity
fi
