#!/bin/bash
set -e
function get_cpu_architecture()
{
    local cpuarch=$(uname -m)
    case $cpuarch in
         x86_64)
              echo "amd64";
              ;;
         aarch64)
              echo "arm64";
              ;;
         *)
              echo "Not supported cpu architecture: ${cpuarch}"  >&2
              exit 1
              ;;
    esac
}
export cpu_arch=$(get_cpu_architecture)

. /.denv

mount -t proc proc /proc
mount -t sysfs sys /sys
ln -s /proc/self/fd /dev/fd

ip addr add 172.16.0.3/24 dev vec0
ip link set dev vec0 address 02:42:ac:10:00:03 
ip link set vec0 up
ip route add default via 172.16.0.1

mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /var/run

cd /etc/wireguard/
wg-quick up wgcf-profile

exec runsvdir /etc/service
