#!/bin/bash
. /.denv
if [[ "$V2RAY" == 1 ]]; then
  echo "v2ray enabled, start"
  v2rayconf=`cat /etc/v2ray/config.json.template`
  array=(${V2RAY_UUIDS//:/ })
  for i in "${!array[@]}"
  do
    uuid=${array[i]}
    v2rayconf=$(echo $v2rayconf | jq ".inbounds[0].settings.clients += [    { \"id\": \"$uuid\", \"level\": 0  } ]" )
  done
  v2rayconf=$(echo $v2rayconf | jq ".inbounds[0].streamSettings.wsSettings.path = \"$V2RAY_PATH\"" ) 
  v2rayconf=$(echo $v2rayconf | jq ".inbounds[0].port = \"$V2RAY_LOCAL_PORT\"" ) 
  echo $v2rayconf | jq '.' > /etc/v2ray/config.json
  pkill v2ray
  exec v2ray -config /etc/v2ray/config.json
else
  echo "v2ray not enabled, down"
  sv down v2ray
  exec sleep infinity
fi
