#!/bin/bash
. /.denv
set -x
if [[ "$AUTOSSH" == 1 ]]; then
  printf -- "${SSH_KEY}" > ~/.ssh/id_rsa
  ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
  printf -- "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
  chmod 600 -R ~/.ssh
  echo "AUTOSSH enabled, start autossh "
  pkill autossh
  exec autossh -M $RSSH_REMOTE_MONITOR_PORT -o StrictHostKeyChecking=no -NR "$RSSH_REMOTE_PORT:localhost:2223" $SSH_USER@$SSH_CONN -p $SSH_CONN_PORT
else
  echo "AUTOSSH not enabled, autossh down"
  sv down autossh
  exec sleep infinity
fi
