#!/bin/bash
. /.denv
if [[ "$COMMAND_SSH" == 1 ]]; then
  echo "command_ssh enabled, up"
  printf -- "${SSH_AUTHED_KEYS}" > ~/.ssh/authorized_keys
  exec /usr/sbin/sshd -D -f /etc/ssh/sshd_nopwd_config
else
  echo "command_ssh not set, down"
  sv down sshd_control
  exec sleep infinity
fi
