#!/bin/bash
. /.denv
if [[ "$JUPYTER" == 1 ]]; then
  echo "jupyter enabled, start"
  export HOME=/root
  export JUPYTER_RUNTIME_DIR=/etc/jupyterlab
  export JUPYTER_PASSWORD_HASHED=$(python3 /root/.jupyter/get_hashed_pwd.py)
  cd /root
  cat /root/.jupyter/jupyter_server_config.py.template | sed -e 's/\${/＄/g' | sed 's/\$/${DOLLAR}/g' | sed 's/＄/${/g' | envsubst > /root/.jupyter/jupyter_server_config.py
  pkill jupyter
  exec jupyter lab
else
  echo "jupyter not enabled, down"
  sv down jupyter
  exec sleep infinity
fi
