#!/bin/bash
. /.denv
if [[ "$AUTOSSH" == 1 ]]; then
  printf -- "${SSH_KEY}" > ~/.ssh/id_rsa
  ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
  printf -- "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
  printf -- "${SSH_AUTHED_KEYS}" > ~/.ssh/authorized_keys
  chmod 600 -R ~/.ssh
  echo "AUTOSSH enabled, start autossh "
  echo autossh -M $RSSH_PROXY_MONITOR_PORT -NR "$RSSH_PROXY_PORT:localhost:2223" $SSH_USER@$SSH_CONN -p $SSH_CONN_PORT
       autossh -M $RSSH_PROXY_MONITOR_PORT -NR "$RSSH_PROXY_PORT:localhost:2223" $SSH_USER@$SSH_CONN -p $SSH_CONN_PORT
else
  echo "AUTOSSH not enabled, autossh down"
  sv dowwn autossh
  sleep infinity
fi
