#!/bin/bash
. /.denv
if [[ "$WG" == 1 ]]; then
  echo "wg enabled"
  set +e
  set -x
  cd /etc/dn42ap
  for scriptname in *.sh; do
    [ -f "$scriptname" ] || continue
    ifname=dn42-${scriptname::-3}
    if wg show "$ifname" ; then
      wg setconf "$ifname" "${scriptname::-3}.conf"
    else
      bash "$scriptname"
    fi
  done
  sleep "$WG_SYNC_INTERVAL"

else
  echo "wg not enabled, down"
  sv down wg_sync
  exec sleep infinity
fi