#!/bin/bash
. /.denv
if [[ "$WG" == 1 ]]; then
  echo "wg enabled"
  set +e
  set -x
  cd /etc/dn42ap
  for f in *.sh; do
    bash "$f"
  done
  birdc configure
  sleep "$WG_SYNC_INTERVAL"

else
  echo "wg not enabled, down"
  sv down wg_sync
  exec sleep infinity
fi

